stack0_driver: stack0_driver.o stack0.o
	g++ -g -Wall -std=c++11 -o stack0_driver stack0_driver.o stack0.o

stack0_driver.o: stack0_driver.cpp
	g++ -g -Wall -std=c++11 -c stack0_driver.cpp

stack0.o: stack0.h stack0.cpp
	g++ -g -Wall -std=c++11 -c stack0.cpp

stack1_driver: stack1_driver.o stack1.o
	g++ -g -Wall -std=c++11 -o stack1_driver stack1_driver.o stack1.o

stack1_driver.o: stack1_driver.cpp
	g++ -g -Wall -std=c++11 -c stack1_driver.cpp

stack1.o: stack1.h stack1.cpp
	g++ -g -Wall -std=c++11 -c stack1.cpp

stack2_driver: stack2_driver.o stack2.o
	g++ -g -Wall -std=c++11 -o stack2_driver stack2_driver.o stack2.o

stack2_driver.o: stack2_driver.cpp
	g++ -g -Wall -std=c++11 -c stack2_driver.cpp

stack2.o: stack2.h stack2.cpp
	g++ -g -Wall -std=c++11 -c stack2.cpp

stack3_driver: stack3_driver.o stack3.o
	g++ -g -Wall -std=c++11 -o stack3_driver stack3_driver.o stack3.o

stack3_driver.o: stack3_driver.cpp
	g++ -g -Wall -std=c++11 -c stack3_driver.cpp

stack3.o: stack3.h stack3.cpp
	g++ -g -Wall -std=c++11 -c stack3.cpp