- View:
    style:
      backgroundColor: red
      width: 50%
      height: 75%
    children:
      - View:
          style:
            backgroundColor: orange
            width: 100
            height: 100
          children:
            - View:
                style:
                  backgroundColor: forestgreen
                  width: 90%
                  height: 80%
      - View:
          style:
            backgroundColor: lightblue
            width: 200
            height: 100 






